//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Donatella.br.com.alquimiacrm.www
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback RetornaEstadosOperationCompleted;

        private System.Threading.SendOrPostCallback RetornaCidadesOperationCompleted;

        private System.Threading.SendOrPostCallback RetornaBairrosOperationCompleted;

        private System.Threading.SendOrPostCallback BuscaCEPOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public Service()
        {
            this.Url = global::Donatella.Properties.Settings.Default.Elatus_br_com_alquimiacrm_www_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event RetornaEstadosCompletedEventHandler RetornaEstadosCompleted;

        /// <remarks/>
        public event RetornaCidadesCompletedEventHandler RetornaCidadesCompleted;

        /// <remarks/>
        public event RetornaBairrosCompletedEventHandler RetornaBairrosCompleted;

        /// <remarks/>
        public event BuscaCEPCompletedEventHandler BuscaCEPCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alquimiacrm.com.br/CEP/Service.asmx/RetornaEstados", RequestNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", ResponseNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RetornaEstados()
        {
            object[] results = this.Invoke("RetornaEstados", new object[0]);
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void RetornaEstadosAsync()
        {
            this.RetornaEstadosAsync(null);
        }

        /// <remarks/>
        public void RetornaEstadosAsync(object userState)
        {
            if ((this.RetornaEstadosOperationCompleted == null))
            {
                this.RetornaEstadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaEstadosOperationCompleted);
            }
            this.InvokeAsync("RetornaEstados", new object[0], this.RetornaEstadosOperationCompleted, userState);
        }

        private void OnRetornaEstadosOperationCompleted(object arg)
        {
            if ((this.RetornaEstadosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaEstadosCompleted(this, new RetornaEstadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alquimiacrm.com.br/CEP/Service.asmx/RetornaCidades", RequestNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", ResponseNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RetornaCidades(string estado)
        {
            object[] results = this.Invoke("RetornaCidades", new object[] {
                        estado});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void RetornaCidadesAsync(string estado)
        {
            this.RetornaCidadesAsync(estado, null);
        }

        /// <remarks/>
        public void RetornaCidadesAsync(string estado, object userState)
        {
            if ((this.RetornaCidadesOperationCompleted == null))
            {
                this.RetornaCidadesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaCidadesOperationCompleted);
            }
            this.InvokeAsync("RetornaCidades", new object[] {
                        estado}, this.RetornaCidadesOperationCompleted, userState);
        }

        private void OnRetornaCidadesOperationCompleted(object arg)
        {
            if ((this.RetornaCidadesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaCidadesCompleted(this, new RetornaCidadesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alquimiacrm.com.br/CEP/Service.asmx/RetornaBairros", RequestNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", ResponseNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] RetornaBairros(string estado, string cidade)
        {
            object[] results = this.Invoke("RetornaBairros", new object[] {
                        estado,
                        cidade});
            return ((string[])(results[0]));
        }

        /// <remarks/>
        public void RetornaBairrosAsync(string estado, string cidade)
        {
            this.RetornaBairrosAsync(estado, cidade, null);
        }

        /// <remarks/>
        public void RetornaBairrosAsync(string estado, string cidade, object userState)
        {
            if ((this.RetornaBairrosOperationCompleted == null))
            {
                this.RetornaBairrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetornaBairrosOperationCompleted);
            }
            this.InvokeAsync("RetornaBairros", new object[] {
                        estado,
                        cidade}, this.RetornaBairrosOperationCompleted, userState);
        }

        private void OnRetornaBairrosOperationCompleted(object arg)
        {
            if ((this.RetornaBairrosCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetornaBairrosCompleted(this, new RetornaBairrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.alquimiacrm.com.br/CEP/Service.asmx/BuscaCEP", RequestNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", ResponseNamespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DadosEndereco BuscaCEP(string cep)
        {
            object[] results = this.Invoke("BuscaCEP", new object[] {
                        cep});
            return ((DadosEndereco)(results[0]));
        }

        /// <remarks/>
        public void BuscaCEPAsync(string cep)
        {
            this.BuscaCEPAsync(cep, null);
        }

        /// <remarks/>
        public void BuscaCEPAsync(string cep, object userState)
        {
            if ((this.BuscaCEPOperationCompleted == null))
            {
                this.BuscaCEPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaCEPOperationCompleted);
            }
            this.InvokeAsync("BuscaCEP", new object[] {
                        cep}, this.BuscaCEPOperationCompleted, userState);
        }

        private void OnBuscaCEPOperationCompleted(object arg)
        {
            if ((this.BuscaCEPCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaCEPCompleted(this, new BuscaCEPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.alquimiacrm.com.br/CEP/Service.asmx")]
    public partial class DadosEndereco
    {

        private string eNDERECOField;

        private string bAIRROField;

        private string cIDADEField;

        private string ufField;

        /// <remarks/>
        public string ENDERECO
        {
            get
            {
                return this.eNDERECOField;
            }
            set
            {
                this.eNDERECOField = value;
            }
        }

        /// <remarks/>
        public string BAIRRO
        {
            get
            {
                return this.bAIRROField;
            }
            set
            {
                this.bAIRROField = value;
            }
        }

        /// <remarks/>
        public string CIDADE
        {
            get
            {
                return this.cIDADEField;
            }
            set
            {
                this.cIDADEField = value;
            }
        }

        /// <remarks/>
        public string UF
        {
            get
            {
                return this.ufField;
            }
            set
            {
                this.ufField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RetornaEstadosCompletedEventHandler(object sender, RetornaEstadosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaEstadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RetornaEstadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RetornaCidadesCompletedEventHandler(object sender, RetornaCidadesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaCidadesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RetornaCidadesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void RetornaBairrosCompletedEventHandler(object sender, RetornaBairrosCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetornaBairrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RetornaBairrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void BuscaCEPCompletedEventHandler(object sender, BuscaCEPCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaCEPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal BuscaCEPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DadosEndereco Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DadosEndereco)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591